In [ ]:
pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo
import numpy as np

np.set_printoptions(threshold=np.inf)
# ------------------------------------

#fetch dataset
balance = fetch_ucirepo(id=12)

#data (as pandas dataframes)
X = balance.data.features
y = balance.data.targets

fitur = np.array(X)
label = np.array(y)

#bineer

panjang = len(label)
target = np.zeros([panjang, 3])
l = []

for i in range(panjang):

  if(label[i] == 'L'):
    target[i, 0:1] = int(1) #[1,0,0]
    target[i, 1:2] = int(0)
    target[i, 2:3] = int(0)
  elif(label[i] == 'B'):
    target[i, 0:1] = int(0) #[0,1,0]
    target[i, 1:2] = int(1)
    target[i, 2:3] = int(0)
  else:
    target[i, 0:1] = int(0) #[0,0,1]
    target[i, 1:2] = int(0)
    target[i, 2:3] = int(1)

  l.append(target[i, :])

target_encode = np.array(l)


print("hasil encode")
print(target_encode)

print("fitru dan label")
data = np.concatenate((fitur, label), axis=1)
print(data)

hasil encode
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0

In [ ]:
from ucimlrepo import fetch_ucirepo
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# np.set_printoptions(threshold=np.inf)

#download dataset
balance = fetch_ucirepo(id=12)

#x = fitur(4), y = label(3)
X = balance.data.features
y = balance.data.targets

#convert ke numpy array
fitur = np.array(X)
label = np.array(y)


panjang = len(label) # total data
target = np.zeros([panjang, 3])   #arr kosong [baris, kolom]
l = []

for i in range(panjang):

  if(label[i] == 'L'):
    target[i, 0:1] = int(1) #[1,0,0]
    target[i, 1:2] = int(0)
    target[i, 2:3] = int(0)
  elif(label[i] == 'B'):
    target[i, 0:1] = int(0) #[0,1,0]
    target[i, 1:2] = int(1)
    target[i, 2:3] = int(0)
  else:
    target[i, 0:1] = int(0) #[0,0,1]
    target[i, 1:2] = int(0)
    target[i, 2:3] = int(1)

  l.append(target[i, :]) #menampung hsl encode
  target_encode = np.array(l) # list to arr numpy


#print("hasil encode")
#print(target_encode)

#print("fitru dan label")
data = np.concatenate((fitur, label), axis=1)
#print(data)

#preprocessing data untuk membagi data training dantesting
#training 70%
#testing 30%
#fitur = soal, target_encode = jawaban dlm bentuk arr
X_train, X_test, y_train, y_test = train_test_split(fitur, target_encode, test_size=0.30, random_state=42)


baris = np.size(X_train, 0)
print(f"baris: {baris}\n")

kolom = np.size(X_train, 1)
print(f"kolom: {kolom}\n")

baris_testing = np.size(X_test, 0)
print(f"baris_testing: {baris_testing}\n")


clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(20, 30), random_state=1)
clf.fit(X_train, y_train) #prosez training

#tes
prediksi = clf.predict(X_test)

#apakah hasil prediksi sama dengan label yang bsebenarnya pada data testing
# cek ukuran variabel prediksi
baris_prediksi = np.size(prediksi, 0)
print(f"baris prediksi: {baris_prediksi}\n")

#cek apakah ada kesalahan prediksi
akurasi = 0
for i in range(baris_prediksi):
  if (prediksi[i, 0]==y_test[i, 0] and prediksi[i, 1]==y_test[i, 1] and prediksi[i, 2]==y_test[i, 2]):
    akurasi = akurasi + 1

print(f"akurasi: {akurasi}\n")
print(f"jumlah prediksi benar: {akurasi} dari {baris_prediksi}\n")
print(f"persentase akurasi: {(akurasi / baris_prediksi) * 100:.2f}%\n")

#sandingkan array x_test dengan prediksi
cek = np.concatenate((y_test, prediksi), axis = 1)

print("lihat antara y_test dan prediksi")
print(cek)


#evaluasi menggunakan metric accuracy
akurasi_sklearn = accuracy_score(y_test, prediksi)
print(f"\nakurasi model: {akurasi_sklearn}")

#confusion
import matplotlib.pyplot as plt
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_test, prediksi)

#f1 skor
from sklearn.metrics import f1_score
print(f1_score(y_test, prediksi, average=None))

#precision
from sklearn.metrics import precision_score
print(precision_score(y_test, prediksi, average=None))

#recall
from sklearn.metrics import recall_score
print(recall_score(y_test, prediksi, average=None))

baris: 437

kolom: 4

baris_testing: 188

baris prediksi: 188

akurasi: 178

jumlah prediksi benar: 178 dari 188

persentase akurasi: 94.68%

lihat antara y_test dan prediksi
[[0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]]

akurasi model: 0.9468085106382979
[0.98765432 0.78787879 0.98342541]
[0.97560976 0.86666667 0.97802198]
[1.         0.72222222 0.98888889]

--- DETAIL PERFORMA PER KELAS ---
Kelas Left (L):
  Precision : 0.9756
  Recall    : 1.0000
  F1-Score  : 0.9877
--------------------
Kelas Balance (B):
  Precision : 0.8667
  Recall    : 0.7222
  F1-Score  : 0.7879
--------------------
Kelas Right (R):
  Precision : 0.9780
  Recall    : 0.9889
  F1-Score  : 0.9834
--------------------
